version: '3.9'

services:
  server:
    container_name: api-server
    image: golang:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    volumes:
      - app:/app
    env_file:
      - .env

volumes:
  app:
